<a href="https://colab.research.google.com/github/nnguyenu/ML-basic/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Basics
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

For example, the array for the coordinates of a point in 3D space, [1, 2, 1], has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

In [2]:
import numpy as np
# initialize array with 2 axes
a = np.array([[1,2,3],[4,5,6.5]])
# init b with specified type  
print(a.size)   # another way to print a
print(a.dtype)     # type of elements in a
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

6
float64
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [ ]:
# create a array full of zeros with size 2x4x5
v = np.zeros((2,4,5))
val = 0
for i in range(2):
  for j in range(4):
    for k in range(5):
      v[i][j][k] = val
      val = val + 1
v

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.]]])

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
a = np.array([2,5,7,9,0])
b = np.array([5,23,67,7,3])
c = a-b
print(c)
print(c**2)
print(10*np.sin(a))
print(a<5)

[ -3 -18 -60   2  -3]
[   9  324 3600    4    9]
[ 9.09297427 -9.58924275  6.56986599  4.12118485  0.        ]
[ True False False False  True]


In [ ]:
a = np.array([[1,2],[3,4]]).T
print(a)

[[1 3]
 [2 4]]


In [14]:
# Convert the input to an array.
np.asarray([[1,2],[3,4]])
a = np.array([[1,2],[3,4]])
b = np.asarray(a)
a

array([[1, 2],
       [3, 4]])

In [10]:
a = [1,2,3,4]
b = np.array([1,2,3])
b.tolist()
c = np.array([[1,4],[2,3]]).tolist()
print(c)

[[1, 4], [2, 3]]


np.hstack(tuple)

Stack arrays in sequence horizontally (column wise).

This is equivalent to concatenation along the second axis, except for 1-D arrays where it concatenates along the first axis

In [17]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
print(np.hstack((a,b)))

a = np.array((1,2,3))
b = np.array((4,5,6))
print(np.hstack((a,b)))

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
